CREATE TABLE IF NOT EXISTS 'User' (
	'user_id' TEXT NOT NULL UNIQUE,
	'username' TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS 'UserDetails' (
	'user_id' TEXT NOT NULL UNIQUE,
	'email' TEXT NOT NULL,
	'real_name' TEXT NOT NULL,
	FOREIGN KEY ("user_id") REFERENCES "User" ("user_id") ON DELETE CASCADE
);