CREATE TABLE IF NOT EXISTS 'User' (
	'userID' TEXT NOT NULL PRIMARY KEY,
	'username' TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS 'UserDetails' (
	'userID' TEXT NOT NULL PRIMARY KEY,
	'email' TEXT NOT NULL,
	'realName' TEXT NOT NULL,
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE CASCADE
);