CREATE TABLE IF NOT EXISTS 'UserPassword' (
	'userID' TEXT NOT NULL PRIMARY KEY,
	'salt' BLOB NOT NULL UNIQUE,
	'hash' BLOB NOT NULL UNIQUE,
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS 'UserAuthToken' (
	'userID' TEXT NOT NULL,
	'token' TEXT NOT NULL UNIQUE,
	'creationTime' INTEGER NOT NULL DEFAULT ( strftime('%s', 'now') ),
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE CASCADE
);