CREATE TABLE IF NOT EXISTS 'Group' (
	'groupID' TEXT NOT NULL PRIMARY KEY,
	'ownerUserID' TEXT NOT NULL,
	'name' TEXT NOT NULL UNIQUE,
	'description' TEXT,
	FOREIGN KEY ("ownerUserID") REFERENCES "User" ("userID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS 'UserGroup' (
	'groupID' TEXT NOT NULL PRIMARY KEY,
	'userID' TEXT NOT NULL,
	FOREIGN KEY ("groupID") REFERENCES "Group" ("groupID") ON DELETE CASCADE,
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS 'ResourceGroup' (
	'groupID' TEXT NOT NULL PRIMARY KEY,
	'resourceID' TEXT NOT NULL,
	'allowedOperations' INTEGER NOT NULL,
	FOREIGN KEY ("groupID") REFERENCES "Group" ("groupID") ON DELETE CASCADE,
	FOREIGN KEY ("resourceID") REFERENCES "Resource" ("resourceID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS 'AdminUser' (
	'userID' TEXT NOT NULL PRIMARY KEY,
	'priority' INTEGER NOT NULL,
	FOREIGN KEY ("userID") REFERENCES "User" ("userID") ON DELETE CASCADE
);